version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - scylla
      - redis

  scylla:
    image: scylladb/scylla:4.5.0
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  scylla_data:
  redis_data: